spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      #?????????????10??
      idle-timeout: 1800000
      #????????10
      maximum-pool-size: 10
      #?????????????
      auto-commit: true
      #?????????0?????????1800000?30???
      max-lifetime: 1800000
      #?????????30000?30??
      connection-timeout: 3000
      #?????????????
      connection-test-query: SELECT 1


  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大阻塞等待时间
        max-wait: -1
        #最大空闲连接数，默认8
        max-idle: 200
        #最小空闲连接数
        min-idle: 5
    password: s123456 # 打包，服务器数据库要用
  web:
    resources:
      #启动默认静态资源处理，默认启用
      add-mappings: true
      cache:
        cachecontrol:
          #缓存相应时间，单位秒
          max-age: 3600
      chain:
        #资源链启动缓存，默认启动
        cache: true
        #启动资源链
        enabled: true
        #压缩资源(gzip,brotli)解析，默认禁用
        compressed: true
      static-locations: classpath:/static/
  #Rabbitmq
  rabbitmq:
    #服务器
    host: 124.220.207.208
    stream:
      #用户名
      username: guest
      #密码
      password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者的最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者，每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认True
        auto-startup: true
        #当消息被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000毫秒
        initial-interval: 1000ms
        #重试次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数，比如2.0，第一次等10s，第二次等20s，第三次等40s
        multiplier: 1

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.seckilldemo.entity

logging:
  level:
    com.example.sekilldemo.mapper: debug